# Monthly GDP by industry - to quarterly
# April 30, 2021

setwd("/Users/philipsmith/Documents/R/NatAccts/Flexible-tables/")
savespot <- "/Users/philipsmith/Documents/R/NatAccts/Flexible-tables/"

pkgs <- c("cansim","tidyverse","lubridate")
inst <- lapply(pkgs,library,character.only=TRUE)

# ser_09, ser_10 and ser_11 are used to partition this very long table
# into three parts of length 96, 96 and 95.

ser_09 <- c(
"REF_DATE",
"All industries [T001]",                                                                                      
"Goods-producing industries [T002]",
"Service-producing industries [T003]",
"Business sector industries [T004]",                                                                          
"Business sector, goods [T005]",                                                                              
"Business sector, services [T006]",                                                                           
"Non-business sector industries [T007]",                                                                      
"Non-business sector, goods [T008]",                                                                          
"Non-business sector, services [T009]",                                                                       
"Industrial production [T010]",                                                                               
"Non-durable manufacturing industries [T011]",                                                                
"Durable manufacturing industries [T012]",                                                                    
"Information and communication technology sector [T013]",                                                     
"Information and communication technology, manufacturing [T014]",                                             
"Information and communication technology, services [T015]",                                                  
"Energy sector [T016]",                                                                                       
"Industrial production (1950 definition) [T017]",                                                             
"Public Sector [T018]",                                                                                       
"Content and media sector [T019]",                                                                            
"All industries (except cannabis sector) [T020]",                                                             
"Cannabis sector [T021]",                                                                                     
"Cannabis sector (licensed) [T022]",                                                                          
"Cannabis sector (unlicensed) [T023]",                                                                        
"All industries (except unlicensed cannabis sector) [T024]",                                                  
"Agriculture, forestry, fishing and hunting [11]",                                                            
"Crop and animal production [11A]",                                                                           
"Crop production [111]",                                                                                      
"Crop production (except cannabis) [111X]",                                                                   
"Cannabis production [111C]",                                                                                 
"Cannabis production (licensed) [111CL]",                                                                     
"Cannabis production (unlicensed) [111CU]",                                                                   
"Animal production [112]",                                                                                    
"Forestry and logging [113]",                                                                                 
"Fishing, hunting and trapping [114]",                                                                        
"Support activities for agriculture and forestry [115]",                                                      
"Mining, quarrying, and oil and gas extraction [21]",                                                         
"Oil and gas extraction [211]",                                                                               
"Oil and gas extraction (except oil sands) [21111]",                                                          
"Oil sands extraction [21114]",                                                                               
"Mining and quarrying (except oil and gas) [212]",                                                            
"Coal mining [2121]",                                                                                         
"Metal ore mining [2122]",                                                                                    
"Iron ore mining [21221]",                                                                                    
"Gold and silver ore mining [21222]",                                                                         
"Copper, nickel, lead and zinc ore mining [21223]",                                                           
"Other metal ore mining [21229]",                                                                             
"Non-metallic mineral mining and quarrying [2123]",                                                           
"Stone mining and quarrying [21231]",                                                                         
"Sand, gravel, clay, and ceramic and refractory minerals mining and quarrying [21232]",                       
"Other non-metallic mineral mining and quarrying [21239]",                                                    
"Potash mining [212396]",                                                                                     
"Other non-metallic mineral mining and quarrying (except potash) [21239X]",                                   
"Support activities for mining and oil and gas extraction [213]",                                             
"Utilities [22]",                                                                                             
"Electric power generation, transmission and distribution [2211]",                                            
"Natural gas distribution [2212]",                                                                            
"Water, sewage and other systems [2213]",                                                                     
"Construction [23]",                                                                                          
"Residential building construction [23A]",                                                                    
"Non-residential building construction [23B]",                                                                
"Repair construction [23D]",                                                                                  
"Engineering and other construction activities [23X]",                                                        
"Manufacturing [31-33]",                                                                                      
"Food manufacturing [311]",                                                                                   
"Animal food manufacturing [3111]",                                                                           
"Grain and oilseed milling [3112]",                                                                           
"Sugar and confectionery product manufacturing [3113]",                                                       
"Fruit and vegetable preserving and specialty food manufacturing [3114]",                                     
"Dairy product manufacturing [3115]",                                                                         
"Meat product manufacturing [3116]",                                                                          
"Seafood product preparation and packaging [3117]",                                                           
"Bakeries and tortilla manufacturing [3118]",                                                                 
"Other food manufacturing [3119]",                                                                            
"Beverage and tobacco product manufacturing [312]",                                                           
"Soft drink and ice manufacturing [31211]",                                                                   
"Breweries [31212]",                                                                                          
"Wineries and distilleries [3121A]",                                                                          
"Tobacco manufacturing [3122]",                                                                               
"Textile, clothing and leather product manufacturing [31X]",                                                  
"Textile and textile product mills [31A]",                                                                    
"Clothing and leather and allied product manufacturing [31B]",                                                
"Wood product manufacturing [321]",                                                                           
"Sawmills and wood preservation [3211]",                                                                      
"Veneer, plywood and engineered wood product manufacturing [3212]",                                           
"Other wood product manufacturing [3219]",                                                                    
"Paper manufacturing [322]",                                                                                  
"Pulp, paper and paperboard mills [3221]",                                                                    
"Converted paper product manufacturing [3222]",                                                               
"Printing and related support activities [323]",                                                              
"Petroleum and coal product manufacturing [324]",                                                             
"Petroleum refineries [32411]",                                                                               
"Petroleum and coal products manufacturing (except petroleum refineries) [3241A]",                            
"Chemical manufacturing [325]",                                                                               
"Basic chemical manufacturing [3251]",                                                                        
"Resin, synthetic rubber, and artificial and synthetic fibres and filaments manufacturing [3252]",            
"Pesticide, fertilizer and other agricultural chemical manufacturing [3253]")                                 

ser_10 <- c(
"REF_DATE",
"Pharmaceutical and medicine manufacturing [3254]",                                                           
"Paint, coating and adhesive manufacturing [3255]",                                                           
"Soap, cleaning compound and toilet preparation manufacturing [3256]",                                        
"Other chemical product manufacturing [3259]",                                                                
"Plastics and rubber products manufacturing [326]",                                                           
"Plastic product manufacturing [3261]",                                                                       
"Rubber product manufacturing [3262]",                                                                        
"Non-metallic mineral product manufacturing [327]",                                                           
"Cement and concrete product manufacturing [3273]",                                                           
"Non-metallic mineral product manufacturing (except cement and concrete products) [327A]",                    
"Primary metal manufacturing [331]",                                                                          
"Iron and steel mills and ferro-alloy manufacturing [3311]",                                                  
"Steel product manufacturing from purchased steel [3312]",                                                    
"Alumina and aluminum production and processing [3313]",                                                      
"Non-ferrous metal (except aluminum) production and processing [3314]",                                       
"Foundries [3315]",                                                                                           
"Fabricated metal product manufacturing [332]",                                                               
"Forging and stamping [3321]",                                                                                
"Architectural and structural metals manufacturing [3323]",                                                   
"Boiler, tank and shipping container manufacturing [3324]",                                                   
"Hardware manufacturing [3325]",                                                                              
"Spring and wire product manufacturing [3326]",                                                               
"Machine shops, turned product, and screw, nut and bolt manufacturing [3327]",                                
"Coating, engraving, heat treating and allied activities [3328]",                                             
"Cutlery, hand tools and other fabricated metal product manufacturing [332A]",                                
"Machinery manufacturing [333]",                                                                              
"Agricultural, construction and mining machinery manufacturing [3331]",                                       
"Industrial machinery manufacturing [3332]",                                                                  
"Commercial and service industry machinery manufacturing [3333]",                                             
"Ventilation, heating, air-conditioning and commercial refrigeration equipment manufacturing [3334]",         
"Metalworking machinery manufacturing [3335]",                                                                
"Engine, turbine and power transmission equipment manufacturing [3336]",                                      
"Other general-purpose machinery manufacturing [3339]",                                                       
"Computer and electronic product manufacturing [334]",                                                        
"Computer and peripheral equipment manufacturing [3341]",                                                     
"Electronic product manufacturing [334B]",                                                                    
"Communications equipment manufacturing [3342]",                                                              
"Semiconductor and other electronic component manufacturing [3344]",                                          
"Other electronic product manufacturing [334A]",                                                              
"Electrical equipment, appliance and component manufacturing [335]",                                          
"Electric lighting equipment manufacturing [3351]",                                                           
"Household appliance manufacturing [3352]",                                                                   
"Electrical equipment manufacturing [3353]",                                                                  
"Other electrical equipment and component manufacturing [3359]",                                              
"Transportation equipment manufacturing [336]",                                                               
"Motor vehicles and parts manufacturing [336Y]",                                                              
"Motor vehicle manufacturing [3361]",                                                                         
"Motor vehicle body and trailer manufacturing [3362]",                                                        
"Motor vehicle parts manufacturing [3363]",                                                                   
"Aerospace product and parts manufacturing [3364]",                                                           
"Miscellaneous transportation equipment manufacturing [336W]",                                                
"Railroad rolling stock manufacturing [3365]",                                                                
"Ship and boat building [3366]",                                                                              
"Other transportation equipment manufacturing [3369]",                                                        
"Furniture and related product manufacturing [337]",                                                          
"Household and institutional furniture and kitchen cabinet manufacturing [3371]",                             
"Office furniture (including fixtures) manufacturing [3372]",                                                 
"Other furniture-related product manufacturing [3379]",                                                       
"Miscellaneous manufacturing [339]",                                                                          
"Medical equipment and supplies manufacturing [3391]",                                                        
"Other miscellaneous manufacturing [3399]",                                                                   
"Wholesale trade [41]",                                                                                       
"Farm product wholesaler-distributors [411]",                                                                 
"Petroleum product wholesaler-distributors [412]",                                                            
"Food, beverage and tobacco wholesaler-distributors [413]",                                                   
"Personal and household goods wholesaler-distributors [414]",                                                 
"Motor vehicle and parts wholesaler-distributors [415]",                                                      
"Building material and supplies wholesaler-distributors [416]",                                               
"Machinery, equipment and supplies wholesaler-distributors [417]",                                            
"Miscellaneous wholesaler-distributors [418]",                                                                
"Wholesale electronic markets, and agents and brokers [419]",                                                 
"Retail trade [44-45]",                                                                                       
"Motor vehicle and parts dealers [441]",                                                                      
"Furniture and home furnishings stores [442]",                                                                
"Electronics and appliance stores [443]",                                                                     
"Building material and garden equipment and supplies dealers [444]",                                          
"Food and beverage stores [445]",                                                                             
"Health and personal care stores [446]",                                                                      
"Gasoline stations [447]",                                                                                    
"Clothing and clothing accessories stores [448]",                                                             
"Sporting goods, hobby, book and music stores [451]",                                                         
"General merchandise stores [452]",                                                                           
"Miscellaneous store retailers [453]",                                                                        
"Miscellaneous store retailers (except cannabis) [453A]",                                                     
"Cannabis stores [453B]",                                                                                     
"Cannabis stores (licensed) [453BL]",                                                                         
"Cannabis stores (unlicensed) [453BU]",                                                                       
"Non-store retailers [454]",                                                                                  
"Retail trade (except unlicensed cannabis) [4AZ]",                                                            
"Transportation and warehousing [48-49]",                                                                     
"Air transportation [481]",                                                                                   
"Rail transportation [482]",                                                                                  
"Water transportation [483]",                                                                                 
"Truck transportation [484]",                                                                                 
"Transit, ground passenger, scenic and sightseeing transportation [48Z]",                                     
"Urban transit systems [4851]")

ser_11 <- c(
"REF_DATE",
"Taxi and limousine service [4853]",                                                                          
"Other transit and ground passenger transportation and scenic and sightseeing transportation [48A]",          
"Pipeline transportation [486]",                                                                              
"Pipeline transportation of natural gas [4862]",                                                              
"Crude oil and other pipeline transportation [486A]",                                                         
"Support activities for transportation [488]",                                                                
"Postal service and couriers and messengers [49A]",                                                           
"Postal service [491]",                                                                                       
"Couriers and messengers [492]",                                                                              
"Warehousing and storage [493]",                                                                              
"Information and cultural industries [51]",                                                                   
"Publishing industries (except Internet) [511]",                                                              
"Motion picture and sound recording industries [512]",                                                        
"Broadcasting (except Internet) [515]",                                                                       
"Radio and television broadcasting [5151]",                                                                   
"Pay and specialty television [5152]",                                                                        
"Telecommunications [517]",                                                                                   
"Data processing, hosting, and related services [518]",                                                       
"Other information services [519]",                                                                           
"Finance and insurance [52]",                                                                                 
"Credit intermediation and monetary authorities [52X]",                                                       
"Depository credit intermediation and monetary authorities [52B]",                                            
"Local credit unions [52213]",                                                                                
"Banking, monetary authorities and other depository credit intermediation [52BX]",                            
"Non-depository credit intermediation and activities related to credit intermediation [522A]",                
"Non-depository credit intermediation [5222]",                                                                
"Activities related to credit intermediation [5223]",                                                         
"Insurance carriers and related activities [524]",                                                            
"Insurance carriers [5241]",                                                                                  
"Agencies, brokerages and other insurance related activities [5242]",                                         
"Financial investment services, funds and other financial vehicles [52A]",                                    
"Real estate and rental and leasing [53]",                                                                    
"Real estate [531]",                                                                                          
"Lessors of real estate [5311]",                                                                              
"Owner-occupied dwellings [5311A]",                                                                           
"Offices of real estate agents and brokers and activities related to real estate [531A]",                     
"Rental and leasing services and lessors of non-financial intangible assets (except copyrighted works) [53B]",
"Rental and leasing services [532]",                                                                          
"Automotive equipment rental and leasing [5321]",                                                             
"Rental and leasing services (except automotive equipment) [532A]",                                           
"Lessors of non-financial intangible assets (except copyrighted works) [533]",                                
"Professional, scientific and technical services [54]",                                                       
"Legal, accounting and related services [541A]",                                                              
"Legal services [5411]",                                                                                      
"Accounting, tax preparation, bookkeeping and payroll services [5412]",                                       
"Architectural, engineering and related services [5413]",                                                     
"Computer systems design and related services [5415]",                                                        
"Advertising, public relations, and related services [5418]",                                                 
"Other professional, scientific and technical services including scientific research and development [541B]", 
"Specialized design services [5414]",                                                                         
"Management, scientific and technical consulting services [5416]",                                            
"Scientific research and development services [5417]",                                                        
"Other professional, scientific and technical services [5419]",                                               
"Management of companies and enterprises [55]",                                                               
"Administrative and support, waste management and remediation services [56]",                                 
"Administrative and support services [561]",                                                                  
"Office administrative services [5611]",                                                                      
"Employment services [5613]",                                                                                 
"Business support services [5614]",                                                                           
"Travel arrangement and reservation services [5615]",                                                         
"Investigation and security services [5616]",                                                                 
"Services to buildings and dwellings [5617]",                                                                 
"Facilities and other support services [561A]",                                                               
"Waste management and remediation services [562]",                                                            
"Educational services [61]",                                                                                  
"Elementary and secondary schools [6111]",                                                                    
"Community colleges and C.E.G.E.P.s [6112]",                                                                  
"Universities [6113]",                                                                                        
"Other educational services [611A]",                                                                          
"Health care and social assistance [62]",                                                                     
"Ambulatory health care services [621]",                                                                      
"Hospitals [622]",                                                                                            
"Nursing and residential care facilities [623]",                                                              
"Social Assistance [624]",                                                                                    
"Health care [62X]",                                                                                          
"Arts, entertainment and recreation [71]",                                                                    
"Performing arts, spectator sports and related industries, and heritage institutions [71A]",                  
"Amusement, gambling and recreation industries [713]",                                                        
"Gambling industries [7132]",                                                                                 
"Amusement and recreation industries [713A]",                                                                 
"Accommodation and food services [72]",                                                                       
"Accommodation services [721]",                                                                               
"Food services and drinking places [722]",                                                                    
"Other services (except public administration) [81]",                                                         
"Repair and maintenance [811]",                                                                               
"Personal and laundry services [812]",                                                                        
"Religious, grant-making, civic, and professional and similar organizations [813]",                           
"Private households [814]",                                                                                   
"Public administration [91]",                                                                                 
"Federal government public administration [911]",                                                             
"Defence services [9111]",                                                                                    
"Federal government public administration (except defence) [911A]",                                           
"Provincial and territorial public administration [912]",                                                     
"Local, municipal and regional public administration [913]",                                                  
"Aboriginal public administration [914]")

table01_id <- "36-10-0434-01" # Monthly GDP by industry
file_refresh <- TRUE
save_file <- paste0(table01_id,".rds")
if(!file.exists(save_file)|file_refresh){
  table01 <- get_cansim(table01_id,refresh=file_refresh)
  saveRDS(table01,file=save_file)
} else {
  table01 <- readRDS(save_file)
}

# Data are available from Jan 1997 forward for 
# 288 industries, but many industries are NA to 
# end of 2006 and all are okay from Jan 2007
q0 <- filter(table01,`Seasonal adjustment`==
  "Seasonally adjusted at annual rates",
  Prices=="Chained (2012) dollars")
q0 <- rename(q0,
  "NAICS"="North American Industry Classification System (NAICS)")
q0 <- select(q0,REF_DATE,NAICS,VALUE)
q0$REF_DATE <- as.Date(paste0(q0$REF_DATE,"-01"))
q1 <- pivot_wider(q0,names_from=NAICS,values_from=VALUE)
q1 <- q1 %>% mutate(Year=year(REF_DATE),Quarter=quarter(REF_DATE),
  Month=month(REF_DATE)) %>% group_by(Year,Quarter) %>%
  summarise(across(2:288,mean)) %>% ungroup()
q1 <- select(q1,-Year,-Quarter)
q1 <- q1[1:97,] # ends March 2021
q1$REF_DATE <- seq.Date(as.Date("1997-01-01"),
  as.Date("2021-01-01"),by = "quarter")
q2 <- select(q1,REF_DATE,everything())
q2 <- mutate(q2,across(2:288,function(x) y <- round(x,0)))
q01 <- select(q2,all_of(ser_09))
q02 <- select(q2,all_of(ser_10))
q03 <- select(q2,all_of(ser_11))
saveRDS(q01,paste0(savespot,"rds/36-10-0434-01.rds"))
saveRDS(q02,paste0(savespot,"rds/36-10-0434-02.rds"))
saveRDS(q03,paste0(savespot,"rds/36-10-0434-03.rds"))
